name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        python -m pytest test_dinox_client.py -v --cov=dinox_client --cov-report=term-missing
    
    - name: Check code quality
      run: |
        pip install black flake8 isort
        black --check dinox_client.py || true
        flake8 dinox_client.py --max-line-length=120 || true
        isort --check-only dinox_client.py || true
      continue-on-error: true
